### ISSUE TITLE
Issue with implementing ctx.i18n.t("...") in Telegraf's "scenes"

### ISSUE THREAD

**Issue by Chococoin** [msaebi031/i18n-telegraf#1]
Hello,

Thank you for your contribution. I am currently exploring how to make ctx.i18n.t("...") work in  Telegraf's "scenes", and I'm encountering some difficulties. I would appreciate any assistance or guidance on this matter.

Could you please provide more information on how to effectively implement ctx.i18n.t("...") into "scenes" in Telegraf? Any examples or code snippets demonstrating the correct usage would be greatly appreciated. Additionally, if there are any specific configurations or dependencies that need to be considered, please let me know.

Thank you in advance for your help. I'm eager to resolve this issue and make progress with my project.

Best regards,
Germán Lugo

**Comment by msaebi031** [comment]
Hello
Use the same as the examples given
And it does not require any special affiliation
But if you need more help, contact me on Telegram
t.me/Target_Designer

‫‪Germán Lugo‬‏ ***@***.***‬‏> در تاریخ یکشنبه ۲۱ مه ۲۰۲۳
ساعت ۱۰:۱۹ نوشت:‬

**Comment by Chococoin** [comment]
Hi msaebi031,

Thank you for your quick response.

I have found a solution.

Inside the Scene file:
`ctx.reply(ctx.scene.ctx.i18n.t("test"))`

The trouble, maybe, was because I was exporting the Scenes from a subfolder.

Best regards.
